### ISSUE TITLE
Material in the intro

### ISSUE THREAD

**Issue by lgatto** [lgatto/2017-04-03-adv-r-progr-EMBL#1]
The material in the introduction contains (so far)
- style (from the defensive programming section)
- writing a function (small part from functional programming)
- apply (small part from functional programming)

My suggestion would be to remove the style section from defensive programming (maybe just add a sentence to remind that this is important in the frame of good programming) and leave the two other topics, as they are short and part of more related content.

Cc: @rstojnic

**Comment by rstojnic** [comment]
Sure, please feel free to reshape as you see fit.
