### ISSUE TITLE
Testing material

### ISSUE THREAD

**Issue by lgatto** [lgatto/2017-04-03-adv-r-progr-EMBL#2]
Quite a bit of content from debug (defensive programming) material overlaps with the
testing section. As the second morning is already quite busy, I suggest to just keep bullet points as reminder in the debugging part. 

Cc: @rstojnic

**Comment by rstojnic** [comment]
Again, please go ahead and remove material from second morning. If we end up with too little (which I doubt) we can always put back some of the functional programming bits. 

Just let me know once you're finished so I can have a look.

**Comment by lgatto** [comment]
Done - not much as been removed, at least nothing that you would have spent a lot of time. There is a bit of repetition (`stop` and `warning`, `tryCatch`), but nothing we would spend a lot of time with, and that is repeated in different contexts anyway.

**Comment by rstojnic** [comment]
Great, thanks! I've also gone through the materials one more time to make sure it makes sense as a story and I think it looks good. I don't think we'll have time to cover anything else, so I'm leaving it as it is.
