### ISSUE TITLE
Update the S4 objects used in Sequences?

### ISSUE THREAD

**Issue by rstojnic** [lgatto/2017-04-03-adv-r-progr-EMBL#3]
I've made a few changes in the ROO teaching material:

- use sequence() instead of seq()
- changed id() into name()
- don't re-declare S4 generics when S3 exists (this is now done automatically by R)

We should probably update the sequences package to reflect these changes at some point?

**Comment by lgatto** [comment]
Ok. There is a `sequence` function, though.

**Comment by rstojnic** [comment]
So what is the preferred solution here, something like this?

`setMethod("sequence", "ANY", function(object,...) base::sequence(object))`

**Comment by rstojnic** [comment]
Added in: ab05dc0291e802ddfc28375fc095f8559db4bcff

**Comment by lgatto** [comment]
I think it should be

```r
.A <- setClass("A", slots = c(a = "numeric"))
a <- .A(a = 1)

setGeneric("sequence", function(nvec, ...) standardGeneric("sequence"))
setMethod("sequence", "ANY", function(nvec) base::sequence(nvec))
setMethod("sequence", "A", function(nvec) print("A.sequnece"))

sequence(1:3)
sequence(a)
```

**Comment by rstojnic** [comment]
base::sequence() is not a generic, so there is no obligation to keep the same parameter names?

**Comment by lgatto** [comment]
1. Set generic, that doesn't exists. ~~Not sure if we need to use `nvec` here. Will test.~~ 
2. Default implementation, that calls the base function, to recover it.
3. New method for our class.

**Comment by lgatto** [comment]
Indeed, we can rename the argument:
```r
.A <- setClass("A", slots = c(a = "numeric"))
a <- .A(a = 1)


setGeneric("sequence", function(x, ...) standardGeneric("sequence"))
setMethod("sequence", "ANY", function(x) base::sequence(x))
setMethod("sequence", "A", function(x) print("A.sequence"))

sequence(1:3)
sequence(a)
```

**Comment by rstojnic** [comment]
Alright then, I'll keep it as it is in the commit quoted above.
